#!/usr/bin/env python3

# TODO

# ensure proper usage
# get tweets
    # use get_user_timeline from helpers.py
        # check if successful (what does the function return if failed?)
        # error message if unsuccessful: sys.exit
    # tokenize tweet
        # use TweetTokenizer to split a tweet into a  list of words (strings)
# initialize Analyzer
# analyze tweets

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # -----ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    # -----get tweets in the form of a list of strings
    tweet_list = helpers.get_user_timeline(sys.argv[1])
    # error check
    if tweet_list == None:
        sys.exit("error getting tweets")

    # -----initialize Analyzer
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # -----analyze tweets
    for tweet in tweet_list:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(str(score) + " " + tweet, "green"))
        elif score < 0.0:
            print(colored(str(score) + " " + tweet, "red"))
        else:
            print(colored(str(score) + " " + tweet, "yellow"))
        
if __name__ == "__main__":
    main()

